#!/bin/bash
WP_OWNER=www-data # <-- wordpress owner
WP_ROOT=${1:-var/www/html/wordpress-5.2.2} # <-- wordpress root directory
WS_GROUP=${2:-www-pub} # <-- webserver group

find ${WP_ROOT} -print -exec chown ${WP_OWNER}:${WS_GROUP} {} \;
find ${WP_ROOT} -print -type d -exec chmod 775 {} \;
find ${WP_ROOT} -print -type f -exec chmod 664 {} \;

# allow wordpress to manage wp-content
find ${WP_ROOT}/wp-content -print -exec chgrp ${WS_GROUP} {} \;
find ${WP_ROOT}/.idea -print -type d -exec chmod 777 {} \;
find ${WP_ROOT}/.idea -print -type f -exec chmod 666 {} \;
